const model = {

    app: {
        page: 'app',
    },

    inputs: {
        answers: [
            {firstAnswer: '',
            isCorrect: '',
        },
            {secondAnswer: '',
            isCorrect: '',
        },
        {thirdAnswer: '',
            isCorrect: '',
        },
        {fourthAnswer: '',
            isCorrect: '',
        },
        ],
    },

    data: {
        questions: [
            {title: 'I hvilken kommune bor det færrest innbyggere?',
             firstOption: 'Aremark',
             secondOption: 'Hattfjelldal',
             thirdOption: 'Utsira',
             fourthOption: 'Kvitsøy',
             hasBeenAnswered: false,
            },
            {title: 'Verdens lengste veitunnel ligger i Norge. Hva heter den?',
             firstOption: 'Lærdalstunnelen',
             secondOption: 'Ryfylketunnelen',
             thirdOption: 'Gudvangatunnelen',
             fourthOption: 'Folgefonntunnelen',
             hasBeenAnswered: false,
            },
            {title: 'Ved hvilken norsk by renner Numedalslågen ut i havet?',
             firstOption: 'Hamar',
             secondOption: 'Grimstad',
             thirdOption: 'Kongsberg',
             fourthOption: 'Larvik',
             hasBeenAnswered: false,
            },
            {title: 'Hvem er vår justis- og beredskapsminister? (2022)',
             firstOption: 'Anniken Huitfeldt',
             secondOption: 'Emilie Mehl',
             thirdOption: 'Sandra Borch',
             fourthOption: 'Ole Borten Moe',
             hasBeenAnswered: false,
            },
            {title: 'Hva er vår nasjonalfugl?',
             firstOption: 'Fossekall',
             secondOption: 'Dompap',
             thirdOption: 'Tiur',
             fourthOption: 'Lundefugl',
             hasBeenAnswered: false,
            },
            {title: 'Hva er vår nasjonalrett?',
             firstOption: 'Sodd',
             secondOption: 'Smalahove',
             thirdOption: 'Fårikål',
             fourthOption: 'Pinnekjøtt',
             hasBeenAnswered: false,
            },
            {title: 'Hvor mange medaljer har Norge tatt i vinter-OL?',
             firstOption: '256',
             secondOption: '175',
             thirdOption: '382',
             fourthOption: '405',
             hasBeenAnswered: false,
            },
            {title: 'Hvilken hunderase var den mest populære i Norge i 2020?',
             firstOption: 'Norsk elghund grå',
             secondOption: 'Engelsk setter',
             thirdOption: 'Golden retriever',
             fourthOption: 'Border collie',
             hasBeenAnswered: false,
            },
        ],
        images: {
            firstQuestion: '<img src="images/gutt1.jpg" alt="Bilde av gutt" class="images"></img>',
            header1: '<img src="images/rosemaling2.png" alt="Rosemaling" class="headerimage"></img>',
            header2: '<img src="images/rosemaling.png" alt="Rosemaling" class="headerimage"></img>',
        },
        correctAnswers: [],
        
    }
}